---
title: "Research"
title-block-banner: true
format:  
  html:
    toc: true
    toc-title: Contents
    toc-location: left
    grid:
      margin-width: 350px
bibliography: references.bib
---

As a forest and ecosystem ecologist, I work in the intersection of paleoecology, landscape ecology and disturbance ecology, using field, lab, and modeling tools. My research is driven by three underlying questions:

1.  *How do changing disturbance regimes alter forest structure and function?*
2.  *How can historical and paleoecologic data be integrated with modeling to anticipate future change?*
3.  *What are the implications of human interventions in changing disturbance regimes?*

To answer those questions, I work across a variety of systems, timescales and disciplines.

### ***How do changing disturbance regimes alter forest structure and function?***

Boreal forest fire frequency has increased in recent decades, causing fire return intervals in some regions to decline from 75-300 years to 30 years or less. Untangling the impact of shorter fire return intervals in boreal forests is critical for anticipating implications for global carbon cycling: shorter intervals between fires disadvantage slower-growing serotinous conifer species but those same conifers produce thick soil organic layers that insulate carbon-rich permafrost. During my PhD, I investigated how short-interval fires altered forest composition, forest carbon and forest structure in boreal Interior Alaska. I quantified forest regeneration in stands that burned once, twice, or three times within 30 years or less, the first empirical study of boreal forests that have experienced three short-interval fires. I demonstrated that reburns drive shifts in forest composition from conifer to deciduous, even in previously-resilient forest types [@hayes2021] and showed that reburning leads to losses in soil carbon that offset gains made from faster-growing deciduous species (Hayes et al., in revision at *Global Change Biology*).

While studying carbon in boreal forests, I started to wonder about the effects of heavy browsing by moose and hare, and the extreme mortality caused by pests and pathogens like aspen leaf miner and canker. I was awarded an [NSF Postdoctoral Fellowship](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2219248&HistoricalAwards=false) to investigate how emerging biotic disturbances like herbivores and insect outbreaks interact with increasing fire frequency to shape ecosystem structure and function in high-latitude forests. Warming temperatures increase the distribution and abundance of biotic agents like aspen leaf miner and canker. Yet relatively little is known about their impact on forest structure and function, particularly when they interact with fire or intense browsing by mammalian herbivores. These disturbances and their interactions could fundamentally alter boreal forests. Working with collaborators at the [Cary Institute of Ecosystem Studies](https://forestfutureslab.org/) and the [University of Saskatchewan](http://npelusask.weebly.com/), I combine landscape simulation modeling with existing empirical data to test mechanistic hypotheses about fire-biotic interactions and their impact on boreal forest succession and carbon. I work with groups like the [Bonanza Creek Long Term Ecological Research Program](https://www.lter.uaf.edu/) to synthesize existing spatial and non-spatial datasets on biotic disturbances and model how organisms like moose, hare, aspen leaf miner and others alter forest composition and carbon through interactions with fire and warming climate.

### ***How can historical and paleoecologic data be integrated with modeling to anticipate future change?***

Increasing fire is driving transformations of boreal forest composition from conifer to broadleaf species. Paleoecologic data hints at the presence of self-regulation, negative feedbacks to fire, a process enabled by an increased dominance of broadleaf species, historically considered less flammable. But it remains unclear whether paleoecologic environments are good analogs for current boreal forests, and whether shifts in forest structure and composition will enable different fire behavior under increasing temperatures. Working with collaborators at the Environmental Defense Fund, Colorado State University, and the University of Montana, I pair empirical measurements of forest structure and composition with late Holocene pollen and charcoal records from lake sediments to test for the possibility, strength or duration of fire self-regulation via increased broadleaf species. As a co-PI on the project, I lead our field measurements, quantifying forest structure and composition in broadleaf stands in boreal forests, data that will be coupled with state-of-the-art physics-based combustion models to examine potential fire behavior (more project details [here](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2215118&HistoricalAwards=false)). Our preliminary fire behavior modeling work has shown that fire spread in reburned landscapes is limited by both fuel and fire weather constraints (link to MS), at least within the first several decades after fire [@buma2022]. 

In addition to my ecological research, I'm very interested in how we do science. While mentoring field assistants as a graduate student, I became passionate about issues of safety and diversity in field research, particularly for early-career scientists. I believe conducting and leading fieldwork is part of the 'hidden curriculum' of many natural science programs -- field research is a critical part of completing many natural science degrees, but opportunities for developing the leadership and management skills required to lead field research safely are limited and often informal [@reichenborn2024]. I developed a survey, asking the natural science community for their perception of the key skills required to lead a field season safely and responsibly. Using the recommendations provided, my colleagues and I produced suggestions for graduate students who lead fieldwork. We also provided suggestions for ways that principal investigators, labs and departments could support graduate fieldwork, including more formal training in skills like wilderness first aid, bystander intervention and conflict resolution [@hayes2022].

If you're interested in hearing me talk more about my work, I've given public seminars at the Cary Institute of Ecosystem studies (link seminar here).
