---
title: "Filtering MTBS perimeters by severity"
subtitle: "+ a primer on Alaska Fire Perimeter Data"
date: "2024-04-15"
categories: [Spatial Analysis, terra]
date-modified: last-modified
format:
  html:
    toc: true
    toc-location: left
    grid:
      margin-width: 350px
reference-location: margin
citation-location: margin
draft: true
bibliography: references.bib
---

As part of my work with the [Past, Present and Future of Boreal Feedbacks](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2215118&HistoricalAwards=false) project, this summer I'll be sampling forest composition and structure in forests that have reburned. One of our early goals with this project was to sample reburned forests off the road system - in part because they tend to go unsampled for obvious reasons[^1], and in part because we're combining modern observations of reburned forests with lake sediment records that provide context on the last 2,500 years of forest composition, and those lakes are off the road system.

[^1]: Alaska is big

Functionally, that means helicopter work (!!). Going into it, I was blinded a bit by the excitement of flying helicopters (beautiful views!!), and hadn't braced myself for some of the challenges - helicopters can only land in so many spots, and it's an expensive privilege, so you can't just wander into the woods and pick a spot[^2].

[^2]: For the record, also not how I pick field sites

I've been digging through fire perimeter datasets, trying to locate fires that overlap.

## Fire perimeter data in Alaska

There are functionally two forms of fire perimeter data in Alaska: the [Alaska Large Fire Database](https://www.frames.gov/catalog/10465) (ALFD) and the [Monitoring Trends in Burn Severity (MTBS)](https://www.mtbs.gov/) dataset. 

### [Alaska Large Fire Database](https://blm-egis.maps.arcgis.com/apps/instant/portfolio/index.html?appid=4841da6a16804c07849c27ea7db2a26b) (ALFD)

The Alaska Large Fire Database, often referred to as "Alaska Large Fire" in my collaborative spaces for reasons I'm realizing I don't know, is maintained by the Alaska Fire Service and contains fire perimeter data from 1942 to the present. It was developed in the 90s when collaborators from the Environmental Research institute of Michigan and the Alaska Interagency Coordination Center digitized and standardized perimeter information from fire reports that dated back to 1942 [@kasischke2002].

Using ground surveys, airborne surveys and aerial or satellite photography

### Monitoring Trends in Burn Severity (MTBS)

MTBS data consists of burn severity and extent information on large fires[^3] across the US from 1984 to the present. Both burn severity and fire extent are derived from Landsat or Sentinel-2 data at a spatial resolution of 30 meters and a temporal resolution of 16 days or so - images are constructed pre- and post-fire to compare Normalized Burn Ratio (NBR) or Differenced Normalized Burn Ratio (dNBR). From there, MTBS depicts severity as a gradient of vegetation response from low (not much vegetation response) to high (potentially complete combustion of vegetation)[^4].

[^3]: defined here as 1,000 acres or bigger in the Western US

[^4]: with additional categories for unburned, increased greenness or outliers caused by clouds, shadows, water bodies, etc

### Difference between ALFD and MTBS

Alaska Large Fire Database has been assumed to overestimate burned area within mapped fire events [@chen2021], and produces consistently higher estimates of area burned across Alaska compared to MTBS. 

In contrast, MTBS has been posited to underestimate burned area, since it excludes fires less than 1000 acres.

Understanding the strengths and drawbacks of both is important - in the context of reburning, MTBS is a particularly useful database - older fire perimeters from ALFD become less precise (cite), sometimes overestimating where the fires overlapped [@buma2022].

\[Brief aside on self-regulating fire\]

## Filtering MTBS in R

I wanted to filter out pixels within MTBS that burned at high severity in both fires.

To do that, I loaded in fire perimeters from XX and XX

\[show code\]

From there, you
